apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qx4y
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0023-tenant/tkrw-pr712-0075-0023-app/devfile-sample-qx4y@sha256:653a0072aca91e86556a0522d20d6b3b54f641787834899dbeb42278fa534c27
        name: my-nodejs
        resources: {}
status: {}
